site_name: IKI Official Site Documentation


theme:
  name: material
  logo: assets/images/logo.svg
  favicon: assets/images/favicon.png
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - navigation.indexes
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      primary: white
      accent: white
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github


markdown_extensions:
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - tables


plugins:
  - search
  - macros


nav:
  - Manual:
    - Manual: index.md 
    - Basics: basics.md
    - Create New Post: creatingNewPostPDP.md
    - SEO: SEO.md
    - Media: media.md
    - Request Additional Resources: requestAdditionalResources.md
    - Othe Site Information: otherSiteInformation.md
  - Notifications:
    - notifications.md


extra:
  mdmBasic:
    CompanyName: Indokoei International
    CompanyAlias: IKI
    CompanyWebAdress: https://indokoei.co.id
    AmbarADS: Ambar ADS
    AmbarADSDeveloperEmail: lukas.ginting@gmail.com
    AdminSite: https://indokoei.co.id/adminsite


extra_css:
  - stylesheets/extra.css


repo_url: https://github.com/ambar-ads/iki-mkdocs-dotcomofficial
repo_name: iki-mkdocs-dotcomofficial

